### ISSUE TITLE
YAAS fails extracting Twitter media

### ISSUE THREAD

**Issue by emansom** [natanlao/yaas#122]
As the long running process [would use a expired guest token](https://github.com/yt-dlp/yt-dlp/pull/5560) that would not be refreshed until restart, [upstream this has been fixed](https://github.com/yt-dlp/yt-dlp/commit/352e7d987323e9df9205ee117a604ee4123231c2).

Update the yt-dlp dependency once a new release is out.

**Comment by natanlao** [comment]
Thanks for the report! I'll merge the Dependabot PR once it lands.
