### ISSUE TITLE
Copying a video from Facebook

### ISSUE THREAD

**Issue by rozwalts** [natanlao/yaas#130]
https://www.facebook.com/watch/?v=605270986682885 

I've never had a problem before. Unknown error: [facebook] 605270986682885: This video is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (facebook) to provide account credentials

**Comment by natanlao** [comment]
Hmm, there doesn't seem to be a recent change to the Facebook extractor in yt-dlp. It looks like the link 404s, which may be why that error is being raised. Are you able to download other Facebook videos?

**Comment by rozwalts** [comment]
Many thanks for your quick reply.  No problems downloading anything else, so it was probably just one of those glitches that happen.  I managed to find the same thing on YouTube, so saved that one instead.  😊

Your help is very much appreciated, at least I know it wasn’t me doing something  wrong!  

Best wishes

Roz Walters

Sent from Mail for Windows

**Comment by natanlao** [comment]
Sweet! I'll mark this closed for now then, but feel free to reopen if you see something off down the line.
